language: ruby
dist: xenial
env:
  global:
    - CC_TEST_REPORTER_ID=378d3d76283637f2d202e9908a5518087a2b1382b782607b6589b990c8f251a3
rvm:
  - 2.7.1
cache: bundler
before_install:
  - gem update --system --conservative
  - gem update bundler --conservative
  - bundle config set deployment 'true'
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bin/rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
